services:
  app:
    extends:
      file: compose.common.yaml
      service: app
    volumes:
      - ./src:/app/src
    container_name: tiketku-backend-dev

  db:
    extends:
      file: compose.common.yaml
      service: db
    container_name: tiketku-db-dev
