services:
  app:
    extends:
      file: compose.common.yaml
      service: app
    build:
      secrets:
        - direct_url
        - database_url
    container_name: plane-ticket
    environment:
      - DEPLOY_DATABASE=${DEPLOY_DATABASE:-false}

  db:
    extends:
      file: compose.common.yaml
      service: db
    container_name: plane-ticket-db
    volumes:
      - db-data:/var/lib/postgresql/data

secrets:
  direct_url:
    environment: DIRECT_URL
  database_url:
    environment: DATABASE_URL

volumes:
  db-data:
