services:
  app:
    extends:
      file: compose.common.yaml
      service: app
    volumes:
      - ./src:/app/src
    container_name: plane-ticket-dev

  db:
    extends:
      file: compose.common.yaml
      service: db
    container_name: plane-ticket-db-dev
