name: Deployment

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  codecov:
    uses: ./.github/workflows/codecov.yaml
    secrets: inherit

  migration:
    uses: ./.github/workflows/migration.yaml
    secrets: inherit

    needs:
      - ci
      - codecov

  deploy:
    name: Build and deploy to Cloud Run
    runs-on: ubuntu-latest

    needs: migration

    permissions:
      id-token: write
      contents: read

    env:
      ARTIFACT_REGISTRY: '${{ VARS.REGION }}-docker.pkg.dev'
      LATEST_DOCKER_IMAGE_TAG: '${{ VARS.REGION }}-docker.pkg.dev/${{ VARS.PROJECT_ID }}/${{ VARS.ARTIFACT_REPO }}/${{ VARS.SERVICE }}:latest'
      CURRENT_DOCKER_IMAGE_TAG: '${{ VARS.REGION }}-docker.pkg.dev/${{ VARS.PROJECT_ID }}/${{ VARS.ARTIFACT_REPO }}/${{ VARS.SERVICE }}:${{ github.sha }}'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'

      - name: Configure Google Cloud to use specific region for the artifact registry
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }} -q

      - name: Authenticate to Docker registry
        uses: docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.ARTIFACT_REGISTRY }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.LATEST_DOCKER_IMAGE_TAG }}
            ${{ env.CURRENT_DOCKER_IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.LATEST_DOCKER_IMAGE_TAG }}
          cache-to: type=inline
          secrets: |
            direct_url=${{ secrets.DIRECT_URL }}
            database_url=${{ secrets.DATABASE_URL }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: '${{ env.CURRENT_DOCKER_IMAGE_TAG }}'
          region: '${{ vars.REGION }}'
          service: '${{ vars.SERVICE }}'
          env_vars: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            DIRECT_URL=${{ secrets.DIRECT_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}
            EMAIL_API_KEY=${{ secrets.EMAIL_API_KEY }}
            VALID_ORIGINS=${{ secrets.VALID_ORIGINS }}
            WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
            STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}
            MIDTRANS_CLIENT_KEY=${{ secrets.MIDTRANS_CLIENT_KEY }}
            MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }}
          env_vars_update_strategy: 'overwrite'
